---
- name: Install dockutil
  homebrew:
    name: dockutil
    update_homebrew: yes

- name: Remove unwanted dock items
  command: dockutil --remove all

- name: Add dock apps
  shell: >
    dockutil --find '{{ item.name }}' ||
    dockutil --add '{{ item.path }}'
  loop:
    - name: Fantastical 2
      path: /Applications/Fantastical 2.app
    - name: Spark
      path: /Applications/Spark.app
    - name: Boostnote
      path: /Applications/Boostnote.app
    - name: Safari
      path: /Applications/Safari.app
    - name: iTerm
      path: /Applications/iTerm.app
    - name: Atom
      path: /Applications/Atom.app
    - name: Fork
      path: /Applications/Fork.app
    - name: Rambox
      path: /Applications/Rambox.app

- name: Add dock folders
  shell: >
    dockutil --find '{{ item.name }}' ||
    dockutil --add '{{ item.path }}' --view {{ item.view }} --display {{ item.display }} --sort {{ item.sort }}
  loop:
    - name: Downloads
      path: ~/Downloads
      view: fan
      display: stack
      sort: dateadded

- name: Set dock size
  command: defaults write com.apple.dock tilesize -int 40
  notify:
    - restart dock

- name: Disable dock recent apps
  command: defaults write ~/Library/Preferences/com.apple.dock show-recents -bool false
  notify:
    - restart dock
