---
- name: Copy gitignore to user home
  copy:
    src: gitignore_global
    dest: '/Users/{{ ansible_user }}/.gitignore_global'

- name: Set global gitignore
  git_config:
    name: core.excludesfile
    scope: global
    value: '/Users/{{ ansible_user }}.gitignore_global'
