---
- name: Install XCode command line tools
  command: xcode-select --install

- name: Install dark-mode
  homebrew:
    name: dark-mode
    update_homebrew: yes
  notify:
    - run homebrew cleanup

- name: Activate macOS dark mode
  command: dark-mode on

- name: Remove dark-mode
  homebrew:
    name: dark-mode
    state: absent

- name: Disable automatic rearrangement of spaces based on most recent use
  command: defaults write com.apple.dock mru-spaces -bool false
  notify:
    - restart dock

- name: Remove GarageBand and data
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - '/Applications/GarageBand.app'
    - '/Library/Application Support/GarageBand'
    - '/Library/Application Support/Logic/'
    - '/Library/Audio/Apple Loops'
    - '/Library/Audio/Apple Loops Index'

- name: Disable Android File Transfer auto-launch on connect
  script: disable_aft.sh
