---
- name: Get MacOS version
  command: sw_vers -productVersion
  register: sw_vers

- name: Set system_macos_version variable
  set_fact:
    system_macos_version: '{{ sw_vers.stdout }}'

- name: Install XCode command line tools
  command: xcode-select --install

- name: Disable automatic rearrangement of spaces based on most recent use
  command: defaults write com.apple.dock mru-spaces -bool false
  notify:
    - restart dock

# MacOS Mojave changes
- name: Re-enable font-smoothing (disabled on MacOS Mojave)
  command: defaults write -g CGFontRenderingFontSmoothingDisabled -bool false
  when: system_macos_version is version('10.14', '>=')

# TODO: Disable Mojave recent apps in dock

- name: Remove GarageBand and data
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - '/Applications/GarageBand.app'
    - '/Library/Application Support/GarageBand'
    - '/Library/Application Support/Logic/'
    - '/Library/Audio/Apple Loops'
    - '/Library/Audio/Apple Loops Index'

- name: Disable Android File Transfer auto-launch on connect
  script: disable_aft.sh
