---

- name: Run git tasks
  include_tasks: git.yml

- name: Run macOS general tasks
  include_tasks: macos.yml

- name: Run bash tasks
  include_tasks: bash.yml

- name: Run Atom text editor tasks
  include_tasks: atom.yml
