---
# Git settings
- name: Copy gitignore to user home
  copy:
    src: gitignore_global
    dest: '/Users/{{ ansible_user }}/.gitignore_global'

- name: Set global gitignore
  git_config:
    name: core.excludesfile
    scope: global
    value: '/Users/{{ ansible_user }}.gitignore_global'

# App Store apps
- name: Install App Store apps
  command: 'mas install {{ item }}'
  loop: '{{ system_appstore_app_ids }}'

# Miniconda3
- name: Download miniconda3 install script
  get_url:
    url: https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
    dest: '/tmp/'
    mode: 0744

- name: Install miniconda3 # TODO: Either resolve bash_profile conflicts or use final version
  shell: /tmp/Miniconda3-latest-MacOSX-x86_64.sh && source ~/.bash_profile

- name: Add conda channels
  command: conda config --add channels {{ item }}
  loop: '{{ system_conda_channels }}'

# OSX
- name: Install XCode command line tools
  command: xcode-select --install

- name: Install dark-mode
  homebrew:
    name: dark-mode
    update_homebrew: yes

- name: Activate macOS dark mode
  command: dark-mode on

- name: Remove dark-mode
  homebrew:
    name: dark-mode
    state: absent

- name: Disable automatic rearrangement of spaces based on most recent use
  command: defaults write com.apple.dock mru-spaces -bool false && killall Dock

- name: Remove GarageBand and data
  command: '{{ item }}'
  loop:
    - rm -rf /Applications/GarageBand.app
    - rm -rf /Library/Application\ Support/GarageBand
    - rm -rf /Library/Application\ Support/Logic/
    - rm -rf /Library/Audio/Apple\ Loops
    - rm -rf /Library/Audio/Apple\ Loops\ Index

- name: Disable Android File Transfer auto-launch on connect
  script: disable_aft.sh

- name: Restore bash_profile
  copy:
    src: bash_profile
    dest: '/Users/{{ ansible_user }}/.bash_profile' # TODO: Source bash_profile

- name: Copy package-list.txt
  copy:
    src: package-list.txt
    dest: '/tmp/package-list.txt'

- name: Install atom packages
  command: apm install --packages-file /tmp/package-list.txt

- name: Restore atom config
  copy:
    src: config.cson
    dest: '/Users/{{ ansible_user }}/.atom/config.cson'
