# ====================
# Python
# ====================

# Link system python before miniconda root environment
PATH="$PATH:$HOME/miniconda3/bin"

# make env with directory name
function mkenv {
	local vers=${1:-3.6}
	local env_name=${PWD##*/}
	echo "Creating Python $vers conda environment: $env_name"
	conda create -y -n $env_name python=$vers
}

# symlink env to miniconda
function linkenv {
	local src=~/miniconda3/envs/${PWD##*/}
	local dest=./venv
	echo "Symlinking $src to $dest"
	ln -s $src $dest
}

# activate env when in working directory
function actenv {
	local env_name=${PWD##*/}
	echo "Activating conda environment: $env_name"
	source activate $env_name
}

# remove env with directory name
function rmenv {
	local env_name=${1:-${PWD##*/}}
	echo "Removing conda environment: $env_name"
	conda remove -y -n $env_name --all
}

# ====================
# Miscellaneous
# ====================

# Enable autocd by typing the folder name only
shopt -s autocd

# ls immediately after cd
function cd {
    builtin cd "$@" && ls
}

# Fix invalid terminal locale issue
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Postgres PGDATA path
export PGDATA=/usr/local/var/postgres/

# Reclaim ctrl-s hotkey for i-search
stty -ixon

# Mozilla SOPS
export SOPS_PGP_FP="31FF21073278DE485F5654781BEE68ADA7161534"

# gpg-agent https://www.gnupg.org/documentation/manuals/gnupg/Invoking-GPG_002dAGENT.html
GPG_TTY=$(tty)
export GPG_TTY
