---
- name: Install dockutil
  homebrew:
    name: dockutil
    update_homebrew: yes

- name: Remove unwanted dock items
  command: dockutil --remove all

- name: Add dock apps
  shell: >
    dockutil --find '{{ item.name }}' ||
    dockutil --add '{{ item.path }}'
  loop: '{{ dock_apps }}'

- name: Add dock folders
  shell: >
    dockutil --find '{{ item.name }}' ||
    dockutil --add '{{ item.path }}' --view {{ item.view }} --display {{ item.display }} --sort {{ item.sort }}
  loop: '{{ dock_folders }}'

- name: Set dock size
  command: defaults write com.apple.dock tilesize -int 40
  notify:
    - restart dock

- name: Disable dock recent apps
  command: defaults write ~/Library/Preferences/com.apple.dock show-recents -bool false
  notify:
    - restart dock
