---
- name: Get MacOS version
  command: sw_vers -productVersion
  register: sw_vers

- name: Set system_macos_version variable
  set_fact:
    system_macos_version: '{{ sw_vers.stdout }}'

- name: Install XCode command line tools
  command: xcode-select --install
  ignore_errors: yes

- name: Disable automatic rearrangement of spaces based on most recent use
  command: defaults write com.apple.dock mru-spaces -bool false
  notify:
    - restart dock

- name: Disable swipe scroll direction
  command: defaults write -g com.apple.swipescrolldirection -bool false

- name: Disable spotlight hotkey
  command: /usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.symbolichotkeys.plist -c "Set AppleSymbolicHotKeys:64:enabled false"

# MacOS Mojave changes
- name: Re-enable font-smoothing (disabled on MacOS Mojave)
  command: defaults write -g CGFontRenderingFontSmoothingDisabled -bool false
  when: system_macos_version is version('10.14', '>=')

- name: Remove GarageBand and data
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - '/Applications/GarageBand.app'
    - '/Library/Application Support/GarageBand'
    - '/Library/Application Support/Logic/'
    - '/Library/Audio/Apple Loops'
    - '/Library/Audio/Apple Loops Index'

- name: Open Android File Transfer to generate Agent
  command: open '/Applications/Android File Transfer.app'

- pause:
    prompt: "Make sure Android File Transfer is initialized"

- name: Kill Android File Transfer
  command: killall 'Android File Transfer'

- name: Disable Android File Transfer auto-launch on connect
  script: disable_aft.sh
