---
- name: Install homebrew formulas
  homebrew:
    name: '{{ homebrew_formulas }}'
    update_homebrew: yes
  notify:
    - run homebrew cleanup

- name: Check and set shell
  include_tasks: tasks/check_shell.yml

- name: Configure homebrew taps
  homebrew_tap:
    name: '{{ item }}'
  loop: '{{ homebrew_taps }}'
  notify:
    - run homebrew cleanup

- name: Install homebrew casks
  homebrew_cask:
    name: '{{ item }}'
    update_homebrew: yes
  loop: '{{ homebrew_casks }}'
  notify:
    - run homebrew cleanup

- name: Install App Store apps
  include_tasks: appstore.yml

- name: Configure git
  include_tasks: git.yml

- name: Configure macOS
  include_tasks: macos.yml

- name: Configure bash
  include_tasks: bash.yml

- name: Configure miniconda
  include_tasks: miniconda.yml

- name: Configure dock
  include_tasks: tasks/dock.yml

- name: Configure Atom
  include_tasks: atom.yml
