---
- name: Symlink miniconda3
  file:
    src: /opt/miniconda3
    dest: /Users/{{ ansible_user }}/miniconda3
    owner: '{{ ansible_user }}'
    group: staff
    state: link

- name: Add conda channels
  shell: /Users/{{ ansible_user }}/miniconda3/bin/conda config --add channels {{ item }}
  loop: '{{ conda_channels }}'
